apiVersion: v1
data:
  password: ZHk2NTQ1Mjg2
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: gitea-auth-secret
  annotations:
    tekton.dev/git-0: http://172.16.30.1:3000
type: kubernetes.io/basic-auth
